# For more information: https://laravel.com/docs/sail
version: '3'
services:
    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: e-abyana-app
        container_name: e-abyana-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: e-abyana-webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
    # MySQL Service
    db:
        image: mysql:8.0
        container_name: e-abyana-db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - dbdata:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network
    # Redis Service
    redis:
        image: redis:alpine
        container_name: e-abyana-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - app-network

# Docker Networks
networks:
    app-network:
        driver: bridge

# Volumes
volumes:
    dbdata:
        driver: local
